---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Ensure NTP is installed
      apt:
        name=ntp
        state=present
    - name: Ensure NTP is running
      service:
        name=ntp
        state=started
        enabled=yes