# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/focal64"

  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    # 256 megabytes
    v.memory = 256
    v.linked_clone = true
  end

  # Server 1
  config.vm.define "server1" do |s1|
    s1.vm.hostname = "orc-s1.test"
    s1.vm.network :private_network, ip: "192.168.69.4"
  end

end
